### ISSUE TITLE
Is there a plan to update with more detailed QC module parameters? 

### ISSUE THREAD

**Issue by TuBieJun** [Sentieon/sentieon-cli#4]
For example, the "--min_map_qua" l in the WgsMetricsAlgo module?

**Comment by TuBieJun** [comment]
and "haploid_bed" argument for DNAscope module?

**Comment by DonFreed** [comment]
Apologies for missing this notification. Arguments for specific tools are documented in the Sentieon manual, https://support.sentieon.com/manual/. For example, the WgsMetricsAlgo is documented at, https://support.sentieon.com/manual/usages/general/#wgsmetricsalgo. Many of the Sentieon tools are designed to match open-source tools from the GATK or Picard, and the argument matching between the tools is documented in a separate application note at, https://support.sentieon.com/appnotes/arguments/#collectwgsmetrics-wgsmetricsalgo.

Pipeline arguments like `--haploid_bed` are documented in the /docs folder, https://github.com/Sentieon/sentieon-cli/blob/main/docs/dnascope-longread.md#alignment-and-variant-calling-from-fastq. Happy to help with any questions that you have regarding specific pipeline arguments.

**Comment by TuBieJun** [comment]
It's okay, I found the documentation and solved the problem.
